name: CI/CD for Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run basic tests (optional)
      - name: Run basic tests
        run: |
          python -m unittest || echo "No tests found"

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t flask-cicd:latest .

      # Step 6: (Optional) Push image to Docker Hub or AWS ECR
      # Uncomment below if you want deployment
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #
      # - name: Push image to DockerHub
      #   run: |
      #     docker tag flask-cicd:latest yourusername/flask-cicd:latest
      #     docker push yourusername/flask-cicd:latest

      # Step 7: Deployment (Optional)
      # Example: deploy to EC2 or render service
      - name: Deploy (placeholder)
        run: echo "Deployment step here (e.g., SSH to EC2 or ECS deploy)"
